config/routes.rb
Rails.application.routes.draw do
  root to: 'folders#index'
  
  resources :notes, only: [:show, :edit, :update, :destroy, :create]
  resources :folders, only: [:show, :destroy, :create]

  get '/search_folder', to: 'folders#search_folder_and_subfolders'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :sub_folders, class_name: 'Folder', foreign_key: :parent_id
  belongs_to :super_folder, class_name: 'Folder', foreign_key: :parent_id, required: false

  scope :roots, -> { where(parent_id: nil) }
  validates :name, uniqueness: true, presence:true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, uniqueness: true, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :destroy]

  # GET /folders
  def index
    @folders = Folder.where(parent_id: nil)
    @notes = Note.where(folder_id: nil)
  end

  # GET /folders/1
  def show
    @sub_folders = @folder.sub_folders
    @notes = Note.where(folder_id: @folder.id)
    get_super_folder_info
  end

  # POST /folders
  def create
    @folder = Folder.new(folder_params)
    if @folder.save
      path = folder_params[:parent_id].present? ? Folder.find(folder_params[:parent_id]) : root_path
      flash[:notice] = 'Folder was successfully created.'
      redirect_to path and return
    else
      flash[:error] = @folder.errors.full_messages[0]
      redirect_to root_path
    end
  end

  # DELETE /folders/1
  def destroy
    path = @folder.parent_id.present? ? Folder.find(@folder.parent_id) : root_path
    @folder.destroy
    flash[:notice] = 'Folder was successfully destroyed.'
    redirect_to path
  end

  # GET /search_folder
  def search_folder_and_subfolders
    @folder = Folder.find_by(name: params[:name]) if params[:name].present?
    path = msg = ''
    if @folder.present?
      path =  @folder
      flash[:notice] = 'Searched successfully'
    else
      path = root_path
      flash[:error] = "Don't have any folder or subfolders with given name"
    end
    redirect_to path
  end

  private
    # Use to get super folder information like id and name
    def get_super_folder_info
      folder = @folder 
      @sup_folders_names = []
      @sup_folders_ids = []
      while folder.super_folder.present? 
        @sup_folders_names.push(folder.super_folder.name)
        @sup_folders_ids.push(folder.super_folder.id)
        folder = folder.super_folder 
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.permit(:name, :parent_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  def index
    @notes = Note.all
  end

  # GET /notes/1
  def show
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    @note = Note.new(note_params)

    if @note.save
      path = note_params[:folder_id].present? ? Folder.find(note_params[:folder_id]) : root_path
      flash[:notice] = 'Note was successfully created.'
      redirect_to path
    else
      flash[:error] = @note.errors.full_messages[0]
      redirect_to root_path
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      flash[:notice] = 'Note was successfully updated.'
      redirect_to @note
    else
      flash[:error] = @note.errors.full_messages[0]
      render :edit
    end
  end

  # DELETE /notes/1
  def destroy
    path = @note.folder_id.present? ? Folder.find(@note.folder_id) : root_path
    @note.destroy
    flash[:notice] = 'Note was successfully destroyed.'
    redirect_to path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.permit(:title, :content, :folder_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/folders/_new_folder_modal.html.erb
<div id="newFolderModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create New Folders</h4>
      </div>
      <div class="modal-body">
        <form action="/folders" class="form-horizontal" data-remote="true" autocomplete="off" style="align-items: center;" method="post">
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
              <%= text_field_tag 'name', nil, class: 'form-control' %>
            </div>
          </div>
          <% if @folder.present? %>
            <%= hidden_field_tag(:parent_id, @folder.id) %>
          <% end %>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= submit_tag 'Create', class: "btn btn-success" %>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/folders/_new_notes_modal.html.erb
<div id="newNotesModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create New Notes</h4>
      </div>
      <div class="modal-body">
        <form action="/notes" class="form-horizontal" data-remote="true" autocomplete="off" style="align-items: center;" method="post">
          <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
              <%= text_field_tag 'title', nil, class: 'form-control folder_name' %>
            </div>
          </div>
          <div class="form-group">
            <label for="content" class="col-sm-2 control-label">content</label>
            <div class="col-sm-10">
              <%= text_area_tag(:content, "", size: "24x6", class: "form-control") %>
            </div>
          </div>
          <% if @folder.present? %>
            <%= hidden_field_tag(:folder_id, @folder.id) %>
          <% end %>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= submit_tag 'Create', class: "btn btn-success" %>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>

app/views/folders/index.html.erb
<div class="main-folder-div row">
  <% @folders.each do |folder| %>
    <div class="col-md-2 text-center">
      <a href="/folders/<%=folder.id%>">
        <%= image_tag 'folder.png', class: "folders-image" %>
        <div class="center-block"><%= folder.name %></div>
      </a>
      <%= link_to 'Delete', "/folders/#{folder.id}", class: "btn btn-default", method: 'delete' %>
    </div>
  <% end %>
</div>

<div class="main-notes-div row">
  <% @notes.each do |note| %>
    <div class="col-md-2 text-center">
      <a href="/notes/<%=note.id%>">
        <%= image_tag 'notes.png', class: "notes-image" %>
        <div class="center-block"><%= note.title %></div>
      </a>
    </div>
  <% end %>
</div>

<div class="new-folder-dailog">
  <%= render 'new_folder_modal' %>
</div>

<div class="new-folder-dailog">
  <%= render 'new_notes_modal' %>
</div>

app/views/folders/show.html.erb
<ol class="breadcrumb parentsFolderNameList">
  <% @sup_folders_names.reverse.each_with_index do | folder, index | %>
    <li>
      <a href="/folders/<%=@sup_folders_ids[@sup_folders_ids.length-index-1]%>">
        <%= folder %>
      </a>
    </li>
  <% end %>
  <li>
    <a href="/folders/<%=@folder.id%>">
      <%= @folder.name %>
    </a>
  </li>
</ol>
  
<div class="main-folder-div row">
  <% @sub_folders.each do |sub_folder| %>
    <div class="col-md-2 text-center">
      <a href="/folders/<%=sub_folder.id%>">
        <%= image_tag 'folder.png', class: "folders-image" %>
        <div class="center-block"><%= sub_folder.name %></div>
      </a>
      <%= link_to 'Delete', "/folders/#{sub_folder.id}", class: "btn btn-default", method: 'delete' %>
    </div>
  <% end %>
</div>
<div class="main-notes-div row">
  <% @notes.each do |note| %>
      <div class="col-md-2 text-center">
      <a href="/notes/<%=note.id%>" >
        <%= image_tag 'notes.png', class: "notes-image" %>
        <div class="center-block"><%= note.title %></div>
      </a>
    </div>
  <% end %>
</div>

<div class="new-folder-dailog">
  <%= render 'new_folder_modal' %>
</div>

<div class="new-folder-dailog">
  <%= render 'new_notes_modal' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading"><h2>Notes App:</h2></div>
        <div class="panel-body">
          <div class="row top-row">
            <div class="col-md-4">
              <div class="home-link">
                <%= link_to 'Home', root_path %>
              </div>    
            </div>
            <div class="col-md-4">
              <%= form_tag(search_folder_path, method: :get) do %>
                <%= text_field_tag :name %>
                <%= submit_tag 'Search' %>
              <% end %>
            </div>
            <div class="col-md-4 text-right">
              <div class="create-links">
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#newFolderModal">New Folder</button>          
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#newNotesModal">New Note</button>            
              </div>
            </div>
          </div>
          <hr/>
          <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %>">
                  <%= value %>
            </div>
          <% end %>
          
          <%= yield %>
        </div>
      </div>      
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true, class: "form-horizontal") do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="title" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
      <%= text_field_tag 'title', @note.title, class: 'form-control folder_name' %>
    </div>
  </div>
  <div class="form-group">
    <label for="content" class="col-sm-2 control-label">content</label>
    <div class="col-sm-10">
      <%= text_area_tag(:content, @note.content, size: "24x6", class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag 'Edit', class: "btn btn-primary" %>
      <%= link_to 'Cancel', root_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h3>Edit Note</h3>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<div class="list-group">
  <span class="list-group-item-heading"><%= @note.title %></span>
    
  <p class="list-group-item-text"><%= @note.content %></p>
</div>

<%= link_to 'Edit', edit_note_path(@note), class: "btn btn-primary" %>

<%= link_to 'Delete', note_path, class: "btn btn-default", method: 'delete' %>